services:
  mongo-db:
    image: mongo:6.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}  # Esta línea crea la base de datos inicial
    volumes:
      - ./mongo:/data/db
    ports:
      - 27018:27017